"use client";

import { useEffect, useState } from "react";

import DashboardShell from "@/components/dashboard-shell";
import NegotiationTimeline from "@/components/negotiation-timeline";
import { fetchProcurements } from "@/services/api";
import { useProtectedRoute } from "@/services/auth";

export default function NegotiationsPage() {
  useProtectedRoute();
  const [procurements, setProcurements] = useState([]);

  useEffect(() => {
    fetchProcurements()
      .then((response) => setProcurements(response.data))
      .catch(() => {});
  }, []);

  return (
    <DashboardShell>
      <div className="space-y-6">
        <div className="panel p-6">
          <h1 className="text-3xl font-semibold text-ink">Negotiation logs</h1>
          <p className="mt-3 text-sm text-slate-500">Audit the multi-turn vendor negotiation trails generated by the NegotiationAgent.</p>
        </div>
        {procurements.map((item) => (
          <div className="panel p-6" key={item.id}>
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-xl font-semibold text-ink">{item.title}</h2>
                <p className="text-sm text-slate-500">{item.category}</p>
              </div>
              <a className="text-sm font-semibold text-signal" href={`/decisions/${item.id}`}>
                Open decision
              </a>
            </div>
            <div className="mt-6">
              <NegotiationTimeline requestId={item.id} />
            </div>
          </div>
        ))}
      </div>
    </DashboardShell>
  );
}
