VENDOR_FIXTURES = [
    {
        "name": "CloudNova Systems",
        "category": "Software",
        "region": "North America",
        "base_price": 1450.0,
        "quality_score": 0.93,
        "reliability_score": 0.91,
        "sustainability_score": 0.82,
        "risk_flags": "",
        "historical_success_rate": 0.94,
        "summary": "Enterprise SaaS vendor with strong implementation support and stable renewal performance.",
    },
    {
        "name": "Vertex Industrial",
        "category": "Hardware",
        "region": "EMEA",
        "base_price": 890.0,
        "quality_score": 0.89,
        "reliability_score": 0.84,
        "sustainability_score": 0.77,
        "risk_flags": "Requires milestone-based delivery oversight.",
        "historical_success_rate": 0.88,
        "summary": "Reliable hardware provider known for strong QA controls and medium delivery complexity.",
    },
    {
        "name": "EcoSource Labs",
        "category": "Packaging",
        "region": "APAC",
        "base_price": 320.0,
        "quality_score": 0.86,
        "reliability_score": 0.83,
        "sustainability_score": 0.95,
        "risk_flags": "",
        "historical_success_rate": 0.9,
        "summary": "Sustainable packaging supplier with strong ESG credentials and flexible volume discounts.",
    },
    {
        "name": "Quantum Office Works",
        "category": "Office Supplies",
        "region": "North America",
        "base_price": 110.0,
        "quality_score": 0.8,
        "reliability_score": 0.88,
        "sustainability_score": 0.78,
        "risk_flags": "",
        "historical_success_rate": 0.86,
        "summary": "High-volume office supplier with predictable delivery and good account management.",
    },
    {
        "name": "BluePeak Global",
        "category": "Software",
        "region": "Cross-border",
        "base_price": 1325.0,
        "quality_score": 0.87,
        "reliability_score": 0.79,
        "sustainability_score": 0.8,
        "risk_flags": "Cross-border support coverage can slow issue escalation.",
        "historical_success_rate": 0.83,
        "summary": "Competitive pricing for procurement software bundles with moderate support escalation risk.",
    },
    {
        "name": "Summit MedTech Supplies",
        "category": "Healthcare",
        "region": "North America",
        "base_price": 640.0,
        "quality_score": 0.91,
        "reliability_score": 0.9,
        "sustainability_score": 0.81,
        "risk_flags": "",
        "historical_success_rate": 0.92,
        "summary": "Healthcare-focused supplier with regulatory discipline and consistent SLA compliance.",
    },
]
